import type { InterventionsData } from "@shared/schema";

export const interventionsData: InterventionsData = {
  version: "1.0",
  categories: {
    sponge_network: {
      id: "sponge_network",
      name: "Sponge Network",
      description: "Water absorption and flood mitigation infrastructure using natural systems",
      icon: "CloudRain",
      color: "#3b82f6",
      applicableTypologies: ["FLOOD", "FLOOD_HEAT", "FLOOD_LANDSLIDE"],
    },
    cooling_network: {
      id: "cooling_network",
      name: "Cooling Network",
      description: "Urban heat island mitigation through green infrastructure and shade provision",
      icon: "Flame",
      color: "#ef4444",
      applicableTypologies: ["HEAT", "FLOOD_HEAT", "HEAT_LANDSLIDE"],
    },
    slope_stabilization: {
      id: "slope_stabilization",
      name: "Slope Stabilization",
      description: "Landslide prevention through bioengineering and vegetation management",
      icon: "Mountain",
      color: "#a16207",
      applicableTypologies: ["LANDSLIDE", "FLOOD_LANDSLIDE", "HEAT_LANDSLIDE"],
    },
    multi_benefit: {
      id: "multi_benefit",
      name: "Multi-Benefit",
      description: "Integrated NbS solutions addressing multiple hazards simultaneously",
      icon: "Leaf",
      color: "#10b981",
      applicableTypologies: ["FLOOD", "HEAT", "LANDSLIDE", "FLOOD_HEAT", "FLOOD_LANDSLIDE", "HEAT_LANDSLIDE", "LOW"],
    },
  },
  interventions: [
    {
      id: "bioswale",
      category: "sponge_network",
      name: "Bioswale",
      description: "Vegetated channels that slow, filter, and infiltrate stormwater runoff",
      osmAssetTypes: ["highway", "drainage"],
      typicalScale: { min: 50, max: 500, unit: "meters" },
      costRange: { min: 50, max: 200, unit: "USD/m" },
      impacts: { flood: "high", heat: "low", landslide: "low" },
      implementationNotes: "Best along roads and parking areas with adequate slope for gravity flow",
      maintenanceRequirements: "Quarterly vegetation management, annual sediment removal",
      timeToImplement: { min: 3, max: 6, unit: "months" },
      cobenefits: ["Water quality improvement", "Habitat creation", "Aesthetic enhancement"],
    },
    {
      id: "rain_garden",
      category: "sponge_network",
      name: "Rain Garden",
      description: "Shallow planted depressions that capture and absorb rainwater from impervious surfaces",
      osmAssetTypes: ["building", "amenity"],
      typicalScale: { min: 10, max: 100, unit: "sqm" },
      costRange: { min: 100, max: 500, unit: "USD/sqm" },
      impacts: { flood: "medium", heat: "low", landslide: "none" },
      implementationNotes: "Suitable near buildings and parking areas with adequate soil infiltration",
      maintenanceRequirements: "Biannual plant care, periodic mulching",
      timeToImplement: { min: 1, max: 3, unit: "months" },
      cobenefits: ["Pollinator habitat", "Property value increase", "Community engagement"],
    },
    {
      id: "permeable_pavement",
      category: "sponge_network",
      name: "Permeable Pavement",
      description: "Porous surface materials allowing stormwater to infiltrate into the ground",
      osmAssetTypes: ["highway", "amenity", "parking"],
      typicalScale: { min: 100, max: 5000, unit: "sqm" },
      costRange: { min: 30, max: 120, unit: "USD/sqm" },
      impacts: { flood: "high", heat: "medium", landslide: "none" },
      implementationNotes: "Replace conventional pavement in low-traffic areas, parking lots, and pedestrian zones",
      maintenanceRequirements: "Annual vacuum sweeping to maintain permeability",
      timeToImplement: { min: 2, max: 6, unit: "months" },
      cobenefits: ["Reduced urban heat", "Groundwater recharge", "Reduced runoff pollution"],
    },
    {
      id: "urban_forest",
      category: "cooling_network",
      name: "Urban Forest / Tree Planting",
      description: "Strategic tree planting to create canopy cover for shade and cooling",
      osmAssetTypes: ["highway", "leisure", "landuse"],
      typicalScale: { min: 500, max: 50000, unit: "sqm" },
      costRange: { min: 15, max: 80, unit: "USD/tree" },
      impacts: { flood: "low", heat: "high", landslide: "medium" },
      implementationNotes: "Select native species adapted to local climate, ensure adequate spacing",
      maintenanceRequirements: "Watering during establishment (2-3 years), periodic pruning",
      timeToImplement: { min: 3, max: 12, unit: "months" },
      cobenefits: ["Carbon sequestration", "Air quality improvement", "Biodiversity", "Mental health"],
    },
    {
      id: "green_roof",
      category: "cooling_network",
      name: "Green Roof",
      description: "Vegetated rooftop systems that reduce heat absorption and manage stormwater",
      osmAssetTypes: ["building"],
      typicalScale: { min: 50, max: 2000, unit: "sqm" },
      costRange: { min: 80, max: 300, unit: "USD/sqm" },
      impacts: { flood: "medium", heat: "high", landslide: "none" },
      implementationNotes: "Requires structural assessment; extensive systems for older buildings",
      maintenanceRequirements: "Seasonal irrigation check, annual plant replacement if needed",
      timeToImplement: { min: 2, max: 8, unit: "months" },
      cobenefits: ["Building energy savings", "Extended roof lifespan", "Urban biodiversity"],
    },
    {
      id: "cool_corridor",
      category: "cooling_network",
      name: "Cool Corridor",
      description: "Shaded pedestrian pathways with trees, water features, and reflective surfaces",
      osmAssetTypes: ["highway", "footway", "cycleway"],
      typicalScale: { min: 200, max: 2000, unit: "meters" },
      costRange: { min: 100, max: 500, unit: "USD/m" },
      impacts: { flood: "low", heat: "high", landslide: "none" },
      implementationNotes: "Prioritize high-pedestrian-traffic routes connecting transit and public spaces",
      maintenanceRequirements: "Regular tree care, surface cleaning, water feature maintenance",
      timeToImplement: { min: 6, max: 18, unit: "months" },
      cobenefits: ["Active transportation", "Public health", "Economic vitality"],
    },
    {
      id: "terracing",
      category: "slope_stabilization",
      name: "Vegetated Terracing",
      description: "Stepped earthworks with deep-rooted vegetation to stabilize hillsides",
      osmAssetTypes: ["natural", "landuse"],
      typicalScale: { min: 100, max: 10000, unit: "sqm" },
      costRange: { min: 50, max: 200, unit: "USD/sqm" },
      impacts: { flood: "medium", heat: "low", landslide: "high" },
      implementationNotes: "Engineering assessment required; combine with drainage systems",
      maintenanceRequirements: "Seasonal inspection, vegetation management, drainage clearing",
      timeToImplement: { min: 6, max: 24, unit: "months" },
      cobenefits: ["Erosion control", "Agricultural potential", "Habitat creation"],
    },
    {
      id: "riparian_buffer",
      category: "multi_benefit",
      name: "Riparian Buffer Zone",
      description: "Vegetated strips along waterways providing flood control, erosion prevention, and habitat",
      osmAssetTypes: ["waterway", "natural"],
      typicalScale: { min: 15, max: 100, unit: "meters width" },
      costRange: { min: 20, max: 100, unit: "USD/m" },
      impacts: { flood: "high", heat: "medium", landslide: "medium" },
      implementationNotes: "Minimum 15m width recommended; use native riparian species",
      maintenanceRequirements: "Invasive species management, periodic replanting",
      timeToImplement: { min: 6, max: 18, unit: "months" },
      cobenefits: ["Water quality", "Fish habitat", "Recreational value", "Carbon storage"],
    },
    {
      id: "wetland_restoration",
      category: "multi_benefit",
      name: "Wetland Restoration",
      description: "Restoring or creating wetlands for flood storage, water treatment, and biodiversity",
      osmAssetTypes: ["natural", "water", "wetland"],
      typicalScale: { min: 1000, max: 100000, unit: "sqm" },
      costRange: { min: 10, max: 80, unit: "USD/sqm" },
      impacts: { flood: "high", heat: "medium", landslide: "low" },
      implementationNotes: "Identify degraded wetland sites or low-lying areas suitable for restoration",
      maintenanceRequirements: "Water level management, invasive species control, monitoring",
      timeToImplement: { min: 12, max: 36, unit: "months" },
      cobenefits: ["Carbon sequestration", "Water treatment", "Biodiversity", "Education"],
    },
    {
      id: "urban_park",
      category: "multi_benefit",
      name: "Urban Park / Green Space",
      description: "Multi-functional green spaces providing cooling, stormwater management, and recreation",
      osmAssetTypes: ["leisure", "landuse"],
      typicalScale: { min: 500, max: 50000, unit: "sqm" },
      costRange: { min: 30, max: 200, unit: "USD/sqm" },
      impacts: { flood: "medium", heat: "high", landslide: "low" },
      implementationNotes: "Design for multiple functions: recreation, stormwater detention, habitat connectivity",
      maintenanceRequirements: "Regular grounds maintenance, facility upkeep, event management",
      timeToImplement: { min: 12, max: 36, unit: "months" },
      cobenefits: ["Public health", "Social cohesion", "Property values", "Biodiversity"],
    },
  ],
};
